// src/ui/react/components/pages/PageContact.js
import React from 'react'

export default React.createClass({
  render() {
    return (
      <div className="aide">
        <h1>Me contacter</h1>
        <p>
          Un bug ? une suggestion ? J'ai besoin de vous pour améliorer ce simulateur qui n'est qu'une première version. N'hésitez pas à me faire part de vos suggestions d'améliorations à l'adresse suivante :
        </p>
        <a className="button" target="_blank" href="https://yineo.fr/contact">Me contacter</a>
      </div>
    )
  }
})

// src/ui/components/PageContact.vue
<script>
  import Component from "../controllers/PageContact.js"
  Component.components = {}
  export default Component;
</script>

<template>
  <div class="component" id="component--page-contact">
    <h1>Me contacter</h1>
    <p>
      Un bug ? une suggestion ? J'ai besoin de vous pour améliorer ce simulateur qui n'est qu'une première version. N'hésitez pas à me faire part de vos suggestions d'améliorations à l'adresse suivante :
    </p>
    <a class="button" target="_blank" href="https://yineo.fr/contact">Me contacter</a>
  </div>
</template>
