// src/ui/react/components/pages/PageAide.js
import React from 'react'

export default React.createClass({
  render() {
    return (
      <div className="aide">
        <h1>Aide</h1>
        <h2>A quoi sert ce simulateur ?</h2>

        <p><strong>Ce simulateur essaie de donner à un dirigeant d'EURL la réponse la plus simple possible à la question complexe "combien il restera à ma société une fois tout payé" ?</strong></p>

        <p>Difficile d'y voir clair dans la fiscalité complexe des sociétés françaises pour un indépendant, celui-ci n'a d'ailleurs que peu de temps pour décortiquer un système qui en demande beaucoup pour être pleinement compris.
          Si bien qu'il est bien difficile pour celui-ci d'avoir une vision claire de ce qu'il lui revient et de ce qu'il devra reverser tôt ou tard aux différents organismes.</p>
        <p>Ce manque de visibilité sur sa trésorerie est dramatique et peut lui coûter la survie de sa structure.</p>
        <p>On lui dit parfois qu'il suffit de mettre la moitié de ce qu'il gagne pour éviter tout souci. Oui mais la moitié de quoi ? De son chiffre d'affaire Hors taxe ? De la rémunération qu'il se verse ? Est-ce vrai pour toutes les situations ?</p>

        <h2>Un simulateur pensé par un indépendant  pour les indépendant</h2>

        <p>Contrairement aux autres simulateurs que vous pourrez trouver, celui-ci de distingue principalement par deux aspects:</p>
        <p>1 - Il se place du point de vue de l'indépendant et pas d'un point de vue comptable</p>
        <p>Ce simulateur présente les choses vues de <strong>votre</strong> coté. Ainsi, on part des sommes Toutes taxes comprises et pas Hors-Taxes : car ce qui transite sur votre compte, c'est du TTC; et ce que vous dépensez, c'est du TTC. De votre point de vue, la TVA est une somme à reverser (ou à recevoir) en fonction des ces deux données.</p>

        <p>2 - on présente ensemble <strong>toutes</strong> les dépenses auxquelles vous pouvez avoir à faire face</p>
        <p> Ainsi vous trouvez au même endroit la prise en compte du calcul de vos cotisations sociales, de la CFE, de l'impots sur les sociétés. Bref, tout ce que <strong>vous allez réellement sortir de votre compte bancaire</strong></p>

        <h2>Comment se servir de ce simulateur ?</h2>

        <p> Entrez des chiffres correspondant à une période d’un an pour être au plus près de la réalité : le simulateur vous donnera le montant que vous devrez provisionner au titre de cette année.</p>

      </div>
    )
  }
})

// src/components/pages/PageAide.vue
<template>
  <div class="component" id="component--page-aide">
    <h1>Aide</h1>
    <h2>A quoi sert ce simulateur ?</h2>

    <p><strong>Ce simulateur essaie de donner à un dirigeant d'EURL la réponse la plus simple possible à la question complexe "combien il restera à ma société une fois tout payé" ?</strong></p>

    <p>Difficile d'y voir clair dans la fiscalité complexe des sociétés françaises pour un indépendant, celui-ci n'a d'ailleurs que peu de temps pour décortiquer un système qui en demande beaucoup pour être pleinement compris.</p>

    <p>Si bien qu'il est bien difficile pour celui-ci d'avoir une vision claire de ce qu'il lui revient et de ce qu'il devra reverser tôt ou tard aux différents organismes.</p>

    <p>Ce manque de visibilité sur sa trésorerie est dramatique et peut lui coûter la survie de sa structure.</p>
    <p>On lui dit parfois qu'il suffit de mettre la moitié de ce qu'il gagne pour éviter tout souci. Oui mais la moitié de quoi ? De son chiffre d'affaire Hors taxe ? De la rémunération qu'il se verse ? Est-ce vrai pour toutes les situations ?</p>

    <h2>Un simulateur pensé par un indépendant  pour les indépendant</h2>

    <p>Contrairement aux autres simulateurs que vous pourrez trouver, celui-ci de distingue principalement par deux aspects:</p>
    <p>1 - Il se place du point de vue de l'indépendant et pas d'un point de vue comptable</p>
    <p>Ce simulateur présente les choses vues de <strong>votre</strong> coté. Ainsi, on part des sommes Toutes taxes comprises et pas Hors-Taxes : car ce qui transite sur votre compte, c'est du TTC; et ce que vous dépensez, c'est du TTC. De votre point de vue, la TVA est une somme à reverser (ou à recevoir) en fonction des ces deux données.</p>

    <p>2 - on présente ensemble <strong>toutes</strong> les dépenses auxquelles vous pouvez avoir à faire face</p>
    <p> Ainsi vous trouvez au même endroit la prise en compte du calcul de vos cotisations sociales, de la CFE, de l'impots sur les sociétés. Bref, tout ce que <strong>vous allez réellement sortir de votre compte bancaire</strong></p>

    <h2>Comment se servir de ce simulateur ?</h2>

    <p> Entrez des chiffres correspondant à une période d’un an pour être au plus près de la réalité : le simulateur vous donnera le montant que vous devrez provisionner au titre de cette année.</p>


  </div>
</template>
