// src/components/site/SiteMenu.vue
<template>
  <div class="menu-centered">
    <ul class="vertical medium-horizontal menu text-centered">
      <li><router-link exact to="/">Simulateur</router-link></li>
      <li><router-link exact to="/aide">Aide</router-link></li>
      <li><router-link exact to="/apropos">A propos de l'auteur</router-link></li>
      <li><router-link exact to="/contact">Contact & feedback</router-link></li>
    </ul>
  </div>
</template>

// src/ui/react/components/site/SiteMenu.js
import React from 'react'
import { Link } from 'react-router'

export default React.createClass({
  render() {
    return (
      <div className="menu-centered">
        <ul className="vertical medium-horizontal menu text-centered">
          <li><Link to="/simulateur" activeClassName="active">Simulateur</Link></li>
          <li><Link to="/aide" activeClassName="active">Aide</Link></li>
          <li><Link to="/contact" activeClassName="active">Contact</Link></li>
        </ul>
        {/* Les composants apparaitront ici */}
        {this.props.children}
      </div>
    )
  }
})
