// src/ui/components/SiteHeader.vue
<script>
  import Component from "../controllers/SiteHeader.js"
  Component.components = {}
  export default Component;
</script>

<template>
  <header class="component" id="site-header">
    <div id="site-title"> Simulateur de trésorerie pour EURL</div>
    <div id="site-subtitle">Professions libérales - Impôt sur les sociétés</div>
  </header>
</template>

// src/ui/react/components/site/SiteHeader.js
import React from "react"

export default React.createClass({
  render() {
    return (
      <header>
        <div id="site-title"> Simulateur de trésorerie pour EURL</div>
        <div id="site-subtitle">Professions libérales - Impôt sur les sociétés</div>
        <div id="version">version <strong>ALPHA</strong> - v 0.9.8 - 22/01/2017</div>
      </header>
    )
  }
})
