// src/ui/react/components/site/SiteHeader.js
import React from "react"

export default React.createClass({
  render() {
    return (
      <header>
        <div id="site-title"> Simulateur de trésorerie pour EURL</div>
        <div id="site-subtitle">Professions libérales - Impôt sur les sociétés</div>
        <div id="version">version <strong>ALPHA</strong> - v 0.9.8 - 22/01/2017</div>
      </header>
    )
  }
})

// src/components/site/SiteHeader.vue
<template>
  <header>
    <div id="site-title"> Simulateur de trésorerie pour EURL</div>
    <div id="site-subtitle">Professions libérales - Impôt sur les sociétés</div>
    <div id="version">version <strong>ALPHA</strong> - v 0.9.8 - 22/01/2017</div>
  </header>
</template>

<style scoped>

  header {
    text-align:center;
    margin-top:1rem;
  }

  #site-title {
    font-size:1.7rem;
    text-transform:uppercase;
  }

  #site-subtitle {
    font-size:1.2rem;
    margin-bottom:0.5rem;
  }

  #version {
    font-style:italic;
    font-size:0.9rem;
    margin:auto;

    margin-bottom:1rem;
  }


</style>
