// src/ui/components/App.vue
<script>
  import Component from "../controllers/App.js";
  import SiteMenu from './SiteMenu'
  import SiteHeader from './SiteHeader'
  import SiteFooter from './SiteFooter'
  Component.components = { SiteMenu, SiteHeader, SiteFooter }
  export default Component
</script>

<template>
  <div id="app">
    <site-menu></site-menu>
    <router-view></router-view>
    <site-footer></site-footer>
  </div>
</template>

// src/ui/react/App.js
import React from 'react'
import SiteMenu from './components/site/SiteMenu'
import SiteHeader from './components/site/SiteHeader'
import SiteFooter from './components/site/SiteFooter'

export default React.createClass({
  render() {
    return (
      <div>
        <SiteHeader />
        <SiteMenu />
        {/* Les composants injectées par react-router apparaitront ici */}
        {this.props.children}
        <SiteFooter />
      </div>
    )
  }
})
