// src/ui/react/components/simulateur/Simulateur.js
import React from 'react';
import SimulateurForm from './SimulateurForm';
import SimulateurResultsSynthese from './SimulateurResultsSynthese';
import SimulateurResultsTable from './SimulateurResultsTable';
import chargesCalculator from "src/services/chargesCalculator";

export default class Simulateur extends React.Component {

  constructor(props) {
    super(props);
    this.state = {
      // résultats du calculator
      Results: {},
      resultClasses: '',
      // paramètres par défaut du calculator
      calculatorParams: {
        chiffreAffaireHt: 0,
        chiffreAffaireTtc: 0,
        fraisHt: 0,
        fraisTtc: 0,
        cfe: 500,
        remuneration: 0,
        prevoyance: 'A'
      }
    };
    this.onFormChange = this.onFormChange.bind(this);
  }

  componentWillMount() {
    this.calculateResults(this.state.calculatorParams);
  }

  calculateResults(params) {
    const Results = chargesCalculator(params);
    this.setState({Results:Results.getResults()});
  }

  onFormChange(formValues) {
    const calculatorParams = Object.assign({}, this.state.calculatorParams);
    for (const property in formValues) {
      if (calculatorParams.hasOwnProperty(property)) {
        calculatorParams[property] = formValues[property];
      }
    }
    this.setState({calculatorParams});
    this.calculateResults(calculatorParams);
  }

  render() {
    return (
      <div id="simulateur">
        <SimulateurForm defaultFormValues={this.state.calculatorParams} onFormChange={this.onFormChange}/>
        <SimulateurResultsSynthese Results={this.state.Results} />
        <div className="row">
          <div className="small-12 columns">
            <SimulateurResultsTable Results={this.state.Results} />
          </div>
        </div>
      </div>
    )
  }

}

// src/components/simulateur/Simulateur.vue
<!--
Composant racine de notre simulateur
-->
<template>

  <div id="simulateur">
    <simulateur-form :formValues="params" @onFormValuesUpdated="setParams"></simulateur-form>
    <simulateur-results-synthese :Results="Results"></simulateur-results-synthese>
    <div class="row">
      <div class="small-12 columns">
        <simulateur-results-table :Results="Results"></simulateur-results-table>
      </div>
    </div>
  </div>

</template>

<script>

  import SimulateurForm from "./simulateurForm"
  import SimulateurResultsTable from "./SimulateurResultsTable"
  import SimulateurResultsSynthese from "./SimulateurResultsSynthese";
  import chargesCalculator from "../../services/chargesCalculator";

  export default {
    data: function() {
      return {
        // paramètres de base pour initier le calcul de nos dettes
        params:  {
          chiffreAffaireHt: 0,
          chiffreAffaireTtc: 0,
          bindToCaHt: true,
          bindToFraisHt: true,
          fraisHt: 0,
          fraisTtc: 0,
          cfe: 200,
          remuneration: 0,
          prevoyance: 'B'
         }
      }
    },
    // calculer les résultats lors de la création de la vue
    created: function() {
      //this.calculateResults();
    },
    computed: {
      Results:function() {
        return chargesCalculator(this.params).getResults();
      }
    },
    methods: {
      // mettre à jour les données de notre simulateur
      setParams:function(formValues) {
         for (const property in formValues) {
            this.params[property] = formValues[property];
         }
         this.calculateResults();
      },
      calculateResults:function() {
        this.Results = chargesCalculator(this.params).getResults();
      }
    },
    components:{
      SimulateurForm,
      chargesCalculator,
      SimulateurResultsTable,
      SimulateurResultsSynthese
    }
  }
</script>

<style>

</style>
